version: "3.7"
services:
  fpm:
    container_name: php_fpm_container
    build:
      context: ./docker
      dockerfile: Dockerfile-php
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www/project/:cached
    environment:
      # Enhanced Xdebug configuration
      PHP_IDE_CONFIG: "serverName=symfony-docker"
      XDEBUG_MODE: "debug"
      XDEBUG_SESSION_START: 1
      XDEBUG_CONFIG: >-
        client_host=host.docker.internal
        client_port=9003
        start_with_request=yes
        log_level=7
        log=/tmp/xdebug.log
    # Ensure these ports are exposed for Xdebug
    expose:
      - 9003
    networks:
      - app_network

  nginx:
    container_name: nginx_container
    build:
      context: ./docker
      dockerfile: Dockerfile-nginx
    volumes:
      - ./:/var/www/project/:cached
    ports:
      - 8080:80
    depends_on:
      - fpm
    networks:
      - app_network

  database:
    container_name: mysql_container
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: cloud-erp
    ports:
      - "3307:3306"
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - app_network

  node:
    image: node:20.17.0
    working_dir: /var/www/project
    volumes:
      - ./:/var/www/project/:cached
    user: "1000:1000" # Use your host user's UID:GID
    expose:
      - "8081"
    command: "npm start"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  database_data: