FROM php:8.2-fpm


RUN apt-get update && apt-get install -y --no-install-recommends \
        git \
        zlib1g-dev \
        libxml2-dev \
        libpng-dev \
        libzip-dev \
        vim curl debconf subversion git apt-transport-https apt-utils \
        build-essential locales acl mailutils wget nodejs zip unzip \
        gnupg gnupg1 gnupg2 \
        sudo \
        ssh \
    && docker-php-ext-install \
        pdo_mysql \
        soap \
        zip \
        opcache \
        gd \
        intl

#RUN pecl install --force xdebug-3.2.1 \
#    && docker-php-ext-enable xdebug
#
## Xdebug Configuration
#RUN { \
#    echo "xdebug.mode=debug,develop"; \
#    echo "xdebug.client_port=9003"; \
#    echo "xdebug.start_with_request=yes"; \
#    echo "xdebug.log=/tmp/xdebug.log"; \
#    echo "xdebug.log_level=7"; \
#    # For Linux, use host network gateway IP
#    echo "xdebug.client_host=host.gateway.internal"; \
#    # Or dynamically find host IP
#    # echo "xdebug.client_host=$(ip route | awk '/default/ { print $3 }')"; \
#} >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

COPY build/php/opcache.ini /usr/local/etc/php/conf.d/
COPY build/php/error_reporting.ini /usr/local/etc/php/conf.d/



RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN curl -sS https://get.symfony.com/cli/installer | bash
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
RUN chmod +x /usr/bin/composer
ENV COMPOSER_ALLOW_SUPERUSER 1

RUN mv /root/.symfony5/bin/symfony /usr/local/bin/symfony


RUN usermod -u 1000 www-data
RUN usermod -a -G www-data root
RUN mkdir -p /var/www
RUN chown -R www-data:www-data /var/www
RUN mkdir -p /var/www/.composer
RUN chown -R www-data:www-data /var/www/.composer
#RUN composer self-update
WORKDIR /var/www/project/
RUN #composer install

# Install Node.js and npm
#RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash - && \
#    apt-get install -y nodejs